console.log ("hello world")
console.log ("Halo, dunia!")
console.log ("Ciao, mondo!")
console.log("Hola, mundo!")
console.log("привет")
console.log("Aloha")
console.log("Merhaba")
console.log("Konnichi wa")
console.log("Olá")
console.log("Kaixo")

